application: socal-jsa
version: 2-1
runtime: java

sessions_enabled: true

welcome_files:
    - index.html

static_files:
    - include: /**.png
    - include: /**.gif
    - include: /**.css
    - include: /**.js
    - include: /**.ico
      expiration: 1d 0h
      
handlers:

- url: /admin/*
  login: admin
  
- url: /admin/conventions
  servlet: org.jsa.socal.mobile.ConventionAdminServlet
  name: Convention Admin
  
- url: /admin/agenda
  servlet: org.jsa.socal.mobile.AgendaAdminServlet
  name: Agenda Admin
  
- url: /conventions
  servlet: org.jsa.socal.mobile.ConventionsServlet
  name: Conventions
  
- url: /convention
  servlet: org.jsa.socal.mobile.ConventionServlet
  name: Convention
  
- url: /agenda
  servlet: org.jsa.socal.mobile.AgendaTopicServlet
  name: AgendaTopic

- url: /links
  jsp: /links.jsp
  
- url: /api/agenda
  servlet: org.jsa.socal.mobile.api.AgendaTopicApi
  name: AgendaTopic Api
  
- url: /api/conventions
  servlet: org.jsa.socal.mobile.api.ConventionsApi
  name: Conventions Api
  
admin_console:
  pages:
  - name: Conventions
    url: /admin/conventions
    
    
