application: socal-jsa
version: 2-5
runtime: java

sessions_enabled: true

welcome_files:
    - index.html

static_files:
    - include: /**.html
    - include: /**.png
    - include: /**.gif
    - include: /**.css
    - include: /**.js
    - include: /**.ico
    - include: /cache.manifest
      expiration: 1d 0h
      
handlers:

- url: /admin/*
  login: admin
  
- url: /admin/conventions
  servlet: org.jsa.socal.mobile.ConventionAdminServlet
  name: Convention Admin
  
- url: /admin/agenda
  servlet: org.jsa.socal.mobile.AgendaAdminServlet
  name: Agenda Admin
  
- url: /api/agenda
  servlet: org.jsa.socal.mobile.api.AgendaTopicApi
  name: AgendaTopic Api
  
- url: /api/conventions
  servlet: org.jsa.socal.mobile.api.ConventionsApi
  name: Conventions Api
  
admin_console:
  pages:
  - name: Conventions
    url: /admin/conventions

web_xml: |
  <mime-mapping>
  	<extension>manifest</extension>
  	<mime-type>text/cache-manifest</mime-type>
  </mime-mapping>
    
    
