application: socal-jsa
version: 3
runtime: java

sessions_enabled: true

welcome_files:
    - index.html

static_files:
    - include: /**.png
    - include: /**.gif
    - include: /**.css
    - include: /**.js
      expiration: 1d 0h
      
handlers:

- url: /admin/*
  login: admin
  
- url: /admin/conventions
  servlet: org.jsa.socal.mobile.ConventionAdminServlet
  name: Convention Admin
  
- url: /admin/debates
  servlet: org.jsa.socal.mobile.DebateAdminServlet
  name: Debate Admin
  
- url: /conventions
  servlet: org.jsa.socal.mobile.ConventionsServlet
  name: Conventions
  
- url: /convention
  servlet: org.jsa.socal.mobile.ConventionServlet
  name: Convention
  
- url: /debate
  servlet: org.jsa.socal.mobile.DebateServlet
  name: Debate

- url: /links
  jsp: /links.jsp
  
admin_console:
  pages:
  - name: Conventions
    url: /admin/conventions
  - name: Debates
    url: /admin/debates
    
    
