application: JSA
version: 1
runtime: java

welcome_files:
    - index.html

handlers:

- url: /admin/*
  login: admin
  
- url: /admin/conventions
  servlet: org.jsa.socal.mobile.ConventionAdminServlet
  name: Convention Admin
  
- url: /admin/debates
  servlet: org.jsa.socal.mobile.DebateAdminServlet
  name: Debate Admin
  
- url: /conventions
  servlet: org.jsa.socal.mobile.ConventionsServlet
  name: Conventions
  
- url: /convention
  servlet: org.jsa.socal.mobile.ConventionServlet
  name: Convention
  
- url: /debate
  servlet: org.jsa.socal.mobile.DebateServlet
  name: Debate
  
admin_console:
  pages:
  - name: Conventions
    url: /admin/conventions
  - name: Debates
    url: /admin/debates